{{- range $idx, $value := .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "base.fullname" $ }}-{{ $value.name }}"
  labels:
    {{- include "base.labels" $ | nindent 4 }}
spec:
  type: {{ $value.type | default "ClusterIP" }}
  ports:
    - port: {{ $value.port }}
      targetPort: {{ $value.targetPort | default $value.port }}
      protocol: {{ $value.protocol | default "TCP" }}
      name: {{ $value.name }}
      {{- if eq "NodePort" ($value.type | default "ClusterIP") }}
      nodePort: {{ $value.nodePort | default $value.port }}
      {{- end }}
  selector:
    {{- include "base.selectorLabels" $ | nindent 4 }}

---
{{ end }}