apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphprotocol-service.fullname" . }}
  labels:
    {{- include "graphprotocol-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "graphprotocol-service.selectorLabels" . | nindent 4 }}
